name: registry

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'infrastructure/registry/**'
      - '.github/workflows/registry.yml'

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}

jobs:
  security:
    name: Run security checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/iac@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high
          file: infrastructure/registry

  test:
    name: Test registry infrastructure
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        name: Checkout code
      - uses: hashicorp/setup-terraform@v3
        name: Install Terraform
        with:
          terraform_version: 1.9.3
          terraform_wrapper: false
      - run: |
          terraform -chdir=infrastructure/registry init -backend=false
          terraform -chdir=infrastructure/registry validate
  format:
    name: Check files format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        name: Checkout code
      - uses: hashicorp/setup-terraform@v3
        name: Install Terraform
        with:
          terraform_version: 1.9.3
          terraform_wrapper: false
      - run: |
          terraform -chdir=infrastructure/registry init -backend=false
          terraform -chdir=infrastructure/registry fmt -check

  create-registry:
    name: Create artefact registry
    needs:
      - security
      - test
      - format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        name: Checkout code
      - uses: hashicorp/setup-terraform@v3
        name: Install Terraform
        with:
          terraform_version: 1.9.3
          terraform_wrapper: false
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      - name: Apply terraform
        run: |          
          terraform -chdir=infrastructure/registry init
          terraform -chdir=infrastructure/registry apply -var-file="production.tfvars" --auto-approve
      - name: Smoke test
        run: |
          aws ecr describe-repositories --repository-names stock-management
